### ISSUE TITLE
During during contract setup, heartbeats do not arrive to the taker

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#723]
Whilst in contract setup, especially in debug mode, some message handlers can take almost 60s to complete (depends on the machine). 
During this time, we cannot process any other message, including heartbeats from the maker.

We should be always able to process heartbeats, regardless of what is going on currently in the actor.

We lack concurrent handling in other places  as well, but this is the most painful in this spot - the lack of processing the heartbeats triggers notification of lost connection and therefore a state change to not being connected to the maker.

note: this issue is especially prevalent in debug builds, calculating the payout curve takes much shorter time in release mode, so this is unlikely a blocker for the Umbrel milestone.

**Comment by klochowicz** [comment]
This was first observed in #682 , and for now a temporary workaround have been used in place (increasing heartbeat interval timeout in debug mode  and watch channel wait timeout it tests)

**Comment by klochowicz** [comment]
It might actually be the sending side that lapses (some excerpt from the tests below):

```
[2mNov 26 15:26:59.474[0m [35mTRACE[0m daemon::send_to_socket: Sending 'Protocol'
[2mNov 26 15:27:09.118[0m [32m INFO[0m daemon::setup_contract: Exchanged signed lock transaction
[2mNov 26 15:27:09.119[0m [35mTRACE[0m daemon::send_to_socket: Sending 'Heartbeat'
```

that 1ms HeartBeat after the previous handler finished is a bit uncanny 😓

**Comment by thomaseizinger** [comment]
Is this still the case, now that we have split the contract setup out into a dedicated actor?

**Comment by thomaseizinger** [comment]
Closing as I think this is resolved. Please re-open if it can be reproduced.

**Comment by klochowicz** [comment]
@thomaseizinger I've just checked whether the workaround was still needed in the tests (it was failing the tests in debug mode if the contract setup took longer before). It doesn't seem to be the case anymore, so that's a win for the contract setup in dedicated actors ✌️ I'll link a cleanup PR here in a sec.

**Comment by klochowicz** [comment]
> @thomaseizinger I've just checked whether the workaround was still needed in the tests (it was failing the tests in debug mode if the contract setup took longer before). It doesn't seem to be the case anymore, so that's a win for the contract setup in dedicated actors ✌️ I'll link a cleanup PR here in a sec.

I've created #906. The PR fails when run on a CI, probably because of less capable machine, but that likely means that this problem is still present (it only concerns debug builds though, so it's a low priority....)
